### ISSUE TITLE
[Bug] Invalid buffer stride error

### ISSUE THREAD

**Issue by oluceps** [hyprwm/hyprpicker#28]
## Version Info
hyprpicker e4c267292a8b983bf84929fdce01cd2b7513518e
hyprland https://github.com/hyprwm/Hyprland/commit/d1a7f1dd368517854fdcc12a9bdd189578eef435

GPU: GTX 750ti with driver version 525.85.05
Installed `hyprpicker` and `hyprland` both through flake in the repo.

## Error
```console
$ hyprpicker
zwlr_screencopy_frame_v1@11: error 1: invalid buffer stride
Segmentation fault (core dumped)
```
```
Starting program: /nix/store/y578shwhgl5qc84da74rrxvng75pg7gx-system-path/bin/hyprpicker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/c35hf8g5b9vksadym9dbjrd6p2y11m8h-glibc-2.35-224/lib/libthread_db.so.1".
zwlr_screencopy_frame_v1@11: error 1: invalid buffer stride

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f5f688 in wl_map_insert_at () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
(gdb) backtrace
#0  0x00007ffff7f5f688 in wl_map_insert_at () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
#1  0x00007ffff7f5ac03 in proxy_destroy () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
#2  0x00007ffff7f5b092 in wl_proxy_marshal_array_flags () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
#3  0x00007ffff7f5b2ae in wl_proxy_marshal_flags () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
#4  0x0000000000405fdb in CLayerSurface::~CLayerSurface() ()
#5  0x0000000000405ba0 in std::unique_ptr<CHyprpicker, std::default_delete<CHyprpicker> >::~unique_ptr() ()
#6  0x00007ffff74400c5 in __run_exit_handlers () from /nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6
#7  0x00007ffff744024e in exit () from /nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6
#8  0x00007ffff7429255 in __libc_start_call_main () from /nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6
#9  0x00007ffff7429309 in __libc_start_main_impl () from /nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6
#10 0x0000000000403cb5 in _start ()
```

## env
```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 23.05 (Stoat), 23.05.20230209.724bfc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(rito): `"home-manager, nixpkgs"`
 - channels(riro): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/usr/.nix-defexpr/channels/nixpkgs`
```

**Comment by vaxerski** [comment]
nvidia is not supported
