### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jamescodesthings** [hyprwm/hyprpicker#32]
Getting a segfault when trying to run `hyprpicker`. Built locally.

uname -a:
`Linux james-xps 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

Trace:
```
(gdb) run
Starting program: /home/james/projects/third-party/hyprpicker/build/hyprpicker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f93e34 in wl_proxy_get_version () from /lib/x86_64-linux-gnu/libwayland-client.so.0
(gdb) bt -full
#0  0x00007ffff7f93e34 in wl_proxy_get_version () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#1  0x000000000040b79a in zwlr_layer_shell_v1_get_layer_surface (zwlr_layer_shell_v1=0x0, surface=0x4513f0, output=0x452190, layer=3, _namespace=0x41134b "hyprpicker")
    at /home/james/projects/third-party/hyprpicker/./wlr-layer-shell-unstable-v1-protocol.h:209
        id = 0x419718 <g_pHyprpicker>
#2  0x000000000040b3a1 in CLayerSurface::CLayerSurface (this=0x451c40, pMonitor=0x450390) at /home/james/projects/third-party/hyprpicker/src/helpers/LayerSurface.cpp:17
No locals.
#3  0x000000000040ef6e in std::make_unique<CLayerSurface, SMonitor*> () at /usr/include/c++/11/bits/unique_ptr.h:962
No locals.
#4  0x000000000040beb0 in CHyprpicker::init (this=0x44bfa0) at /home/james/projects/third-party/hyprpicker/src/hyprpicker.cpp:21
        m = std::unique_ptr<SMonitor> = {get() = 0x450390}
        __for_range = std::vector of length 1, capacity 1 = {std::unique_ptr<SMonitor> = {get() = 0x450390}}
        __for_begin = std::unique_ptr<SMonitor> = {get() = 0x450390}
        __for_end = std::unique_ptr<SMonitor> = {get() = 0x0}
#5  0x0000000000410639 in main (argc=1, argv=0x7fffffffe068, envp=0x7fffffffe078) at /home/james/projects/third-party/hyprpicker/src/main.cpp:64
No locals.
(gdb) 
```

**Comment by Rishabh672003** [comment]
update to the latest hyprland-git and this gets fixed
