### ISSUE TITLE
[destroyed object]: error 1: Invalid stride（10240）

### ISSUE THREAD

**Issue by LeoGitHuber** [hyprwm/hyprpicker#49]
System: ArchLinux with Nvidia
```
[WARN] 24 bit formats are unsupported, hyprpicker may or may not work as intended!
[destroyed object]: error 1: Invalid stride (10240)
Segmentation fault (core dumped)
```
The output of `bt -full` is listed below.
```
#0  0x00007ffff7f3e415 in  () at /usr/lib/libwayland-client.so.0
#1  0x00007ffff7f3e573 in  () at /usr/lib/libwayland-client.so.0
#2  0x00007ffff7f40132 in wl_proxy_marshal_array_flags () at /usr/lib/libwayland-client.so.0
#3  0x00007ffff7f40bda in wl_proxy_marshal_flags () at /usr/lib/libwayland-client.so.0
#4  0x000000000040bbd8 in wl_surface_destroy(wl_surface*) (wl_surface=0x45ca70)
    at /usr/include/wayland-client-protocol.h:3733
#5  0x000000000040b9db in CLayerSurface::~CLayerSurface() (this=0x45c8b0, __in_chrg=<optimized out>)
    at /home/Leo/Personal/hyprpicker/src/helpers/LayerSurface.cpp:37
#6  0x000000000040b564 in std::default_delete<CLayerSurface>::operator()(CLayerSurface*) const
    (this=0x45e8e0, __ptr=0x45c8b0) at /usr/include/c++/13.2.1/bits/unique_ptr.h:99
#7  0x000000000040b4d2 in std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >::~unique_ptr() (this=0x45e8e0, __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/unique_ptr.h:404
        __ptr = @0x45e8e0: 0x45c8b0
#8  0x000000000040b457 in std::destroy_at<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> > >(std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*) (__location=0x45e8e0)
    at /usr/include/c++/13.2.1/bits/stl_construct.h:88
#9  0x000000000040b3ff in std::_Destroy<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> > >(std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*) (__pointer=0x45e8e0)
    at /usr/include/c++/13.2.1/bits/stl_construct.h:149
#10 0x000000000040b39e in std::_Destroy_aux<false>::__destroy<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*>(std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*, std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*) (__first=0x45e8e0, __last=0x45e8e8)
    at /usr/include/c++/13.2.1/bits/stl_construct.h:163
--Type <RET> for more, q to quit, c to continue without paging--
 >*>(std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*, std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*) (__first=0x45e8e0, __last=0x45e8e8)
    at /usr/include/c++/13.2.1/bits/stl_construct.h:196
#12 0x000000000040b102 in std::_Destroy<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*, std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> > >(std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*, std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >*, std::allocator<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> > >&)
    (__last=0x45e8e8, __first=0x45e8e0) at /usr/include/c++/13.2.1/bits/alloc_traits.h:947
#13 std::vector<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> >, std::allocator<std::unique_ptr<CLayerSurface, std::default_delete<CLayerSurface> > > >::~vector()
    (this=0x4566d8, __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_vector.h:732
#14 0x000000000040afca in CHyprpicker::~CHyprpicker() (this=0x456640, __in_chrg=<optimized out>) at /home/Leo/Personal/hyprpicker/src/helpers/../hyprpicker.hpp:16
#15 0x000000000040b006 in std::default_delete<CHyprpicker>::operator()(CHyprpicker*) const (this=0x4196d8 <g_pHyprpicker>, __ptr=0x456640) at /usr/include/c++/13.2.1/bits/unique_ptr.h:99
#16 0x000000000040af2a in std::unique_ptr<CHyprpicker, std::default_delete<CHyprpicker> >::~unique_ptr() (this=0x4196d8 <g_pHyprpicker>, __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/unique_ptr.h:404
        __ptr = @0x4196d8: 0x456640
#17 0x00007ffff745ecc6 in  () at /usr/lib/libc.so.6
#18 0x00007ffff745ee10 in  () at /usr/lib/libc.so.6
#19 0x00007ffff7445cd7 in  () at /usr/lib/libc.so.6
#20 0x00007ffff7445d8a in __libc_start_main () at /usr/lib/libc.so.6
#21 0x00000000004045d5 in _start ()
```

**Comment by vaxerski** [comment]
> `[WARN] 24 bit formats are unsupported, hyprpicker may or may not work as intended!`

> Nvidia

what do you expect?

update your hyprland, if it's not up to date. Other than that, out of luck.
