### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by tannerellen** [hyprwm/hyprpicker#89]
Attempting to launch hyprpicker on the last few git releases gives a segmentation fault error on arch. Everything before commit c9238d39f64dd2618975c9d654301a4720659aed (core: move to hyprwayland-scanner) works fine anything after that commit crashes with the segmentation fault so that is the bad commit.

I'm on the latest git for everything using paru. hyprwayland-scanner is reporting version: hyprwayland-scanner-git 0.4.2.r1.g500c81a9-1

Someone else reported in discord so it's not just me :-) https://discord.com/channels/961691461554950145/961694014615208048/1290176764299051030

**Comment by solopasha** [comment]
backtrace: 
```gdb
(gdb) bt full
#0  0x000055df079a6dc0 in operator() (r=<optimized out>, when=<optimized out>, __closure=0x55df46473a50) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/helpers/LayerSurface.cpp:96
        this = 0x55da1bb35773
        this = <optimized out>
#1  std::__invoke_impl<void, CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)>&, CCWlCallback*, unsigned int> (__f=...) at /usr/include/c++/14/bits/invoke.h:61
No locals.
#2  std::__invoke_r<void, CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)>&, CCWlCallback*, unsigned int> (__fn=...) at /usr/include/c++/14/bits/invoke.h:111
No locals.
#3  std::_Function_handler<void(CCWlCallback*, unsigned int), CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)> >::_M_invoke(const std::_Any_data &, CCWlCallback *&&, unsigned int &&) (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/14/bits/std_function.h:290
No locals.
#4  0x000055df079ac049 in std::function<void(CCWlRegistry*, unsigned int)>::operator() (this=<optimized out>, __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/14/bits/std_function.h:587
No locals.
#5  _CWlCallbackDone (resource=<optimized out>, data=<optimized out>, callback_data=<optimized out>) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/protocols/wayland.cpp:234
        PO = <optimized out>
#6  _CWlCallbackDone (data=<optimized out>, resource=<optimized out>, callback_data=<optimized out>) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/protocols/wayland.cpp:231
        PO = <optimized out>
#7  0x00007f33de2c4056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
No locals.
#8  0x00007f33de2bf74d in ffi_call_int (cif=cif@entry=0x7ffcd0a7a490, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
        classes = {X86_64_INTEGERSI_CLASS, X86_64_NO_CLASS, 3727460432, 32563}
        stack = 0x7ffcd0a7a210 "P\242\247\320\374\177"
        argp = 0x7ffcd0a7a2d0 ""
        arg_types = <optimized out>
        gprcount = 3
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        flags = <optimized out>
        reg_args = 0x7ffcd0a7a210
#9  0x00007f33de2c264e in ffi_call (cif=cif@entry=0x7ffcd0a7a490, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffcd0a7a560) at ../src/x86/ffi64.c:710
        arg_types = 0x7ffcd0a7a4b0
        i = <optimized out>
        nargs = 3
        max_reg_struct_size = <optimized out>
#10 0x00007f33de59310e in wl_closure_invoke (closure=closure@entry=0x55df464da920, target=<optimized out>, target@entry=0x55df46471990, opcode=opcode@entry=0, data=<optimized out>, flags=1)
    at ../src/connection.c:1228
        count = 1
        cif = {abi = FFI_UNIX64, nargs = 3, arg_types = 0x7ffcd0a7a4b0, rtype = 0x7f33de2c87b0 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = {0x7f33de2c88b0 <ffi_type_pointer>, 0x7f33de2c88b0 <ffi_type_pointer>, 0x7f33de2c8850 <ffi_type_uint32>, 0xc, 0x55df4646a330, 0x0, 0x8, 0x55df4646a458, 0x7ffcd0a7a6c0, 
          0x7f33de59441e <wl_display_read_events+174>, 0xc, 0x7f33de59237d <close_fds+141>, 0x55df46473b2c, 0x55df4646a520, 0xa4, 0x55df4646a3d8, 0x55df46497450, 0x7ffcd0a7a600, 0xc, 0x55df46497388, 
          0x55df4649745c, 0x55df4646a330}
        ffi_args = {0x7ffcd0a7a470, 0x7ffcd0a7a478, 0x55df464da938, 0x0, 0x55df079b9d98 <_CWlDisplayEvents+24>, 0x55df4646a458, 0x0, 0x0, 0x75, 0x55df00000000, 0x7ffcd0a7a5e0, 0x2, 0x7ffcd0a7a600, 0x80, 
          0x0, 0x100000001, 0x55df4646d40c, 0x1c4, 0x7ffcd0a7a630, 0x7f33dde8b5ac <_int_free_create_chunk+156>, 0xc000100000001, 0xffffffffffffff60}
        implementation = <optimized out>
#11 0x00007f33de593979 in dispatch_event (display=display@entry=0x55df4646a330, queue=queue@entry=0x55df4646a428) at ../src/wayland-client.c:1670
        closure = 0x55df464da920
        proxy = 0x55df46471990
        opcode = 0
        proxy_destroyed = <optimized out>
#12 0x00007f33de593d73 in dispatch_queue (display=0x55df4646a330, queue=0x55df4646a428) at ../src/wayland-client.c:1816
        count = 4
        count = <optimized out>
        err = <optimized out>
#13 wl_display_dispatch_queue_pending (display=0x55df4646a330, queue=0x55df4646a428) at ../src/wayland-client.c:2058
        ret = <optimized out>
#14 0x000055df079a0e8d in CHyprpicker::init (this=0x55df46469820) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/hyprpicker.cpp:112
No locals.
#15 main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/main.cpp:79
        long_options = {{name = 0x55df079b12f6 "autocopy", has_arg = 0, flag = 0x0, val = 97}, {name = 0x55df079b0d74 "format", has_arg = 1, flag = 0x0, val = 102}, {name = 0x55df079b12ff "help", 
--Type <RET> for more, q to quit, c to continue without paging--c
            has_arg = 0, flag = 0x0, val = 104}, {name = 0x55df079b1304 "no-fancy", has_arg = 0, flag = 0x0, val = 110}, {name = 0x55df079b130d "render-inactive", has_arg = 0, flag = 0x0, val = 114}, {
            name = 0x55df079b131d "no-zoom", has_arg = 0, flag = 0x0, val = 122}, {name = 0x55df079b1325 "no-fractional", has_arg = 0, flag = 0x0, val = 116}, {name = 0x55df079b1333 "quiet", has_arg = 0, 
            flag = 0x0, val = 113}, {name = 0x55df079b1339 "verbose", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55df079b1341 "version", has_arg = 0, flag = 0x0, val = 86}, {name = 0x0, has_arg = 0, 
            flag = 0x0, val = 0}}
```

**Comment by vaxerski** [comment]
great stacktrace, can you build in debug? 

aint crashin for me

**Comment by solopasha** [comment]
```gdb
#0  0x0000563905554495 in operator() (__closure=0x56392926a430, r=0x56392926a430, when=12696931)
    at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/helpers/LayerSurface.cpp:96
        this = 0x563c4ab41a9a
#1  0x0000563905557148 in std::__invoke_impl<void, CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)>&, CCWlCallback*, unsigned int>(std::__invoke_other, struct {...} &, CCWlCallback *&&, unsigned int &&) (__f=...) at /usr/include/c++/14/bits/invoke.h:61
No locals.
#2  0x0000563905556c98 in std::__invoke_r<void, CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)>&, CCWlCallback*, unsigned int>(struct {...} &, CCWlCallback *&&, unsigned int &&) (__fn=...)
    at /usr/include/c++/14/bits/invoke.h:111
No locals.
#3  0x0000563905555e74 in std::_Function_handler<void(CCWlCallback*, unsigned int), CLayerSurface::markDirty()::<lambda(CCWlCallback*, uint32_t)> >::_M_invoke(const std::_Any_data &, CCWlCallback *&&, unsigned int &&) (__functor=..., __args#0=@0x7ffdac882610: 0x56392926a430, 
    __args#1=@0x7ffdac88260c: 12696931) at /usr/include/c++/14/bits/std_function.h:290
No locals.
#4  0x0000563905575f61 in std::function<void(CCWlCallback*, unsigned int)>::operator() (
    this=0x56392926a430, __args#0=0x56392926a430, __args#1=12696931)
    at /usr/include/c++/14/bits/std_function.h:591
No locals.
#5  0x000056390556f6bc in _CWlCallbackDone (data=0x56392926a430, resource=0x5639292d1a70, 
    callback_data=12696931) at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/protocols/wayland.cpp:234
        PO = 0x56392926a430
#6  0x00007f9f9226f056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
No locals.
#7  0x00007f9f9226a74d in ffi_call_int (cif=cif@entry=0x7ffdac882840, fn=<optimized out>, 
    rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:673
        classes = {X86_64_INTEGERSI_CLASS, X86_64_NO_CLASS, 2452043856, 32671}
        stack = 0x7ffdac8825c0 "0\244&)9V"
        argp = 0x7ffdac882680 ""
        arg_types = <optimized out>
        gprcount = 3
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        flags = <optimized out>
        reg_args = 0x7ffdac8825c0
#8  0x00007f9f9226d64e in ffi_call (cif=cif@entry=0x7ffdac882840, fn=<optimized out>, 
    rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffdac882910) at ../src/x86/ffi64.c:710
        arg_types = 0x7ffdac882860
        i = <optimized out>
        nargs = 3
        max_reg_struct_size = <optimized out>
#9  0x00007f9f9245810e in wl_closure_invoke (closure=closure@entry=0x56392927b2a0, 
    target=<optimized out>, target@entry=0x5639292d1a70, opcode=opcode@entry=0, data=<optimized out>, 
    flags=1) at ../src/connection.c:1228
        count = 1
        cif = {abi = FFI_UNIX64, nargs = 3, arg_types = 0x7ffdac882860, 
          rtype = 0x7f9f922737b0 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = {0x7f9f922738b0 <ffi_type_pointer>, 0x7f9f922738b0 <ffi_type_pointer>, 
          0x7f9f92273850 <ffi_type_uint32>, 0xc, 0x563929261330, 0x0, 0x8, 0x563929261458, 
          0x7ffdac882a70, 0x7f9f9245941e <wl_display_read_events+174>, 0xc, 
          0x7f9f9245737d <close_fds+141>, 0x5639292688fc, 0x563929261520, 0xa4, 0x5639292613d8, 
          0x563929291240, 0x7ffdac8829b0, 0xc, 0x563929291178, 0x56392929124c, 0x563929261330}
        ffi_args = {0x7ffdac882820, 0x7ffdac882828, 0x56392927b2b8, 0x0, 
          0x5639055b7bb8 <_CWlDisplayEvents+24>, 0x563929261458, 0x0, 0x0, 0x75, 0x0, 0x7ffdac882990, 
          0x2, 0x7ffdac8829b0, 0x80, 0x0, 0x100000001, 0x56392926440c, 0x1c4, 0x7ffdac8829e0, 
          0x7f9f91da55ac <_int_free_create_chunk+156>, 0xc000100000001, 0xffffffffffffff60}
        implementation = <optimized out>
#10 0x00007f9f92458979 in dispatch_event (display=display@entry=0x563929261330, 
    queue=queue@entry=0x563929261428) at ../src/wayland-client.c:1670
        closure = 0x56392927b2a0
        proxy = 0x5639292d1a70
        opcode = 0
        proxy_destroyed = <optimized out>
#11 0x00007f9f92458d73 in dispatch_queue (display=0x563929261330, queue=0x563929261428)
    at ../src/wayland-client.c:1816
        count = 4
        count = <optimized out>
        err = <optimized out>
#12 wl_display_dispatch_queue_pending (display=0x563929261330, queue=0x563929261428)
    at ../src/wayland-client.c:2058
        ret = <optimized out>
#13 0x00005639055606e5 in CHyprpicker::init (this=0x563929260820)
    at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/hyprpicker.cpp:112
No locals.
#14 0x000056390556e6fd in main (argc=1, argv=0x7ffdac882cb8, envp=0x7ffdac882cc8)
    at /usr/src/debug/hyprpicker-0.4.0-1.fc41.x86_64/src/main.cpp:79
        long_options = {{name = 0x563905594ce4 "autocopy", has_arg = 0, flag = 0x0, val = 97}, {
            name = 0x563905594ced "format", has_arg = 1, flag = 0x0, val = 102}, {
            name = 0x563905594cf4 "help", has_arg = 0, flag = 0x0, val = 104}, {
            name = 0x563905594cf9 "no-fancy", has_arg = 0, flag = 0x0, val = 110}, {
            name = 0x563905594d02 "render-inactive", has_arg = 0, flag = 0x0, val = 114}, {
            name = 0x563905594d12 "no-zoom", has_arg = 0, flag = 0x0, val = 122}, {
            name = 0x563905594d1a "no-fractional", has_arg = 0, flag = 0x0, val = 116}, {
            name = 0x563905594d28 "quiet", has_arg = 0, flag = 0x0, val = 113}, {
            name = 0x563905594d2e "verbose", has_arg = 0, flag = 0x0, val = 118}, {
            name = 0x563905594d36 "version", has_arg = 0, flag = 0x0, val = 86}, {name = 0x0, 
            has_arg = 0, flag = 0x0, val = 0}}
```

**Comment by vaxerski** [comment]
tehee oopsie
